# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: authoring/XmCloudAuthoring.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

  deploy:
    needs: build    # Deploy will wait for successful build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Sitecore CLI and Configure NuGet Source
        run: |
          sitecore plugin init --overwrite
          dotnet nuget add source -n Sitecore https://nuget.sitecore.com/resources/v3/index.json
          dotnet tool install Sitecore.CLI

      - name: Add Serialization Plugin
        run: dotnet sitecore plugin add -n Sitecore.DevEx.Extensibility.Serialization

      - name: Sitecore Cloud Login
        run: dotnet sitecore cloud login --client-credentials --client-id "CO0beGq5WWwqqiupp3OzmC0eqOB1L3ud" --client-secret "Rnv2NcFEchrNVFqtUFb1Y0em_TUYVZfpRDaQSenw-Yx68F1jJFMkRARSU7FOvHwA"

      - name: Connect to Environment
        run: dotnet sitecore cloud environment connect --environment-id "264fhT4Z1SNi1kBjPrVJrs"

      - name: Create Deployment
        run: dotnet sitecore cloud deployment create --environment-id "264fhT4Z1SNi1kBjPrVJrs"

      - name: Push Serialized Items
        run: dotnet sitecore ser push --environment-name "deployment"
